//! The [`Amendment`] node — an immutable change record evolving the
//! shape and constraint graphs over time.
//!
//! Once a shape or constraint reaches `promoted` or `canonical`, all
//! subsequent changes are recorded as Amendments rather than direct
//! edits. Each amendment carries `targets` (the IDs it modifies),
//! `initiated_by` (human / ai / system), and the standard intent +
//! evidence + provenance fields.

use std::collections::BTreeMap;
use std::fmt;

use serde::de::{self, MapAccess, Visitor};
use serde::ser::SerializeMap;
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use clap::ValueEnum;

use super::{
    AmendmentId, ConstraintId, Evidence, Intent, ProfileId, Provenance, Realization, ShapeId,
    Status,
};

/// Semver-style impact classification for an amendment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VersionImpact {
    /// Breaking change.
    Major,
    /// Backwards-compatible enhancement.
    Minor,
    /// Backwards-compatible fix.
    Patch,
}

/// Who initiated an amendment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InitiatedType {
    /// Authored directly by a human.
    Human,
    /// Authored by an AI agent.
    Ai,
    /// Generated by an automated system or migration.
    System,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Amendment {
    pub id: AmendmentId,
    pub name: String,
    pub description: String,
    pub targets: AmendmentTargets,
    pub status: Status,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_impact: Option<VersionImpact>,
    pub intent: Intent,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub constraints: Vec<ConstraintId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub realization: Vec<Realization>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub evidence: Vec<Evidence>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub provenance: Vec<Provenance>,
    pub initiated_by: InitiatedBy,
    /// Display-only archival state. When archived, the amendment is
    /// hidden from listing output by default. Validation, reciprocity
    /// (INV-019), and CI-002 enforcement always see the full set
    /// regardless of this flag.
    #[serde(default, skip_serializing_if = "Archived::is_no")]
    pub archived: Archived,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub metadata: BTreeMap<String, serde_yaml_ng::Value>,
}

impl Amendment {
    /// Returns `true` when this amendment has been archived and should
    /// be hidden from default listing output.
    #[must_use]
    pub fn is_archived(&self) -> bool {
        self.archived.is_yes()
    }
}

impl super::traits::GraphNode for Amendment {
    type Id = super::AmendmentId;

    fn raw_id(&self) -> u64 {
        self.id.get()
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn status(&self) -> &super::Status {
        &self.status
    }

    fn intent(&self) -> &super::Intent {
        &self.intent
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AmendmentTargets {
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub shape_ids: Vec<ShapeId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub constraint_ids: Vec<ConstraintId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub profile_ids: Vec<ProfileId>,
}

impl AmendmentTargets {
    /// Returns `true` when the amendment targets no nodes at all.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.shape_ids.is_empty() && self.constraint_ids.is_empty() && self.profile_ids.is_empty()
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InitiatedBy {
    #[serde(rename = "type")]
    pub initiated_type: InitiatedType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<String>,
}

/// Display-only archival state for an amendment.
///
/// Serializes as one of three forms:
///
/// - Field omitted entirely → `Archived::No` (the default)
/// - `archived: true` → `Archived::Yes(ArchivedDetail { reason: None })`
/// - `archived: { reason: "..." }` → `Archived::Yes(ArchivedDetail { reason: Some("...") })`
///
/// The `false` literal is accepted on deserialization but never emitted:
/// the field is simply omitted via `skip_serializing_if`.
#[derive(Debug, Clone, PartialEq)]
pub enum Archived {
    /// Not archived — amendment appears in default listings.
    No,
    /// Archived — hidden from default listings.
    Yes(ArchivedDetail),
}

impl Default for Archived {
    fn default() -> Self {
        Archived::No
    }
}

impl Archived {
    /// Returns `true` when the amendment is archived.
    #[must_use]
    pub fn is_yes(&self) -> bool {
        matches!(self, Archived::Yes(_))
    }

    /// Returns `true` when the amendment is not archived.
    #[must_use]
    pub fn is_no(&self) -> bool {
        matches!(self, Archived::No)
    }

    /// Returns the archival reason, if any.
    #[must_use]
    pub fn reason(&self) -> Option<&str> {
        match self {
            Archived::No => None,
            Archived::Yes(detail) => detail.reason.as_deref(),
        }
    }

    /// Constructs an `Archived::Yes` with no reason.
    #[must_use]
    pub fn yes() -> Self {
        Archived::Yes(ArchivedDetail::default())
    }

    /// Constructs an `Archived::Yes` with a reason.
    #[must_use]
    pub fn yes_with_reason(reason: impl Into<String>) -> Self {
        Archived::Yes(ArchivedDetail {
            reason: Some(reason.into()),
        })
    }
}

/// Optional detail attached to an archived amendment.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ArchivedDetail {
    /// Free-form explanation of why this amendment was archived.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl Serialize for Archived {
    /// Emits `true` when no detail is present, or `{reason: "..."}` when
    /// a reason is attached. `Archived::No` is never serialized — the
    /// parent struct's `skip_serializing_if` omits the field entirely.
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Archived::No => serializer.serialize_bool(false),
            Archived::Yes(detail) if detail.reason.is_none() => serializer.serialize_bool(true),
            Archived::Yes(detail) => {
                let mut map = serializer.serialize_map(Some(1))?;
                map.serialize_entry("reason", detail.reason.as_ref().unwrap())?;
                map.end()
            }
        }
    }
}

impl<'de> Deserialize<'de> for Archived {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        deserializer.deserialize_any(ArchivedVisitor)
    }
}

struct ArchivedVisitor;

impl<'de> Visitor<'de> for ArchivedVisitor {
    type Value = Archived;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("a boolean or a map like {reason: \"...\"}")
    }

    fn visit_bool<E: de::Error>(self, v: bool) -> Result<Archived, E> {
        if v {
            Ok(Archived::Yes(ArchivedDetail::default()))
        } else {
            Ok(Archived::No)
        }
    }

    fn visit_map<M: MapAccess<'de>>(self, map: M) -> Result<Archived, M::Error> {
        let detail =
            ArchivedDetail::deserialize(de::value::MapAccessDeserializer::new(map))?;
        Ok(Archived::Yes(detail))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn archived_roundtrip_bare_true() {
        let archived = Archived::yes();
        let yaml = serde_yaml_ng::to_string(&archived).unwrap();
        assert_eq!(yaml.trim(), "true");
        let parsed: Archived = serde_yaml_ng::from_str(&yaml).unwrap();
        assert_eq!(parsed, archived);
    }

    #[test]
    fn archived_roundtrip_bare_false() {
        let archived = Archived::No;
        let yaml = serde_yaml_ng::to_string(&archived).unwrap();
        assert_eq!(yaml.trim(), "false");
        let parsed: Archived = serde_yaml_ng::from_str(&yaml).unwrap();
        assert_eq!(parsed, archived);
    }

    #[test]
    fn archived_roundtrip_with_reason() {
        let archived = Archived::yes_with_reason("Changes integrated");
        let yaml = serde_yaml_ng::to_string(&archived).unwrap();
        assert!(yaml.contains("reason"));
        assert!(yaml.contains("Changes integrated"));
        let parsed: Archived = serde_yaml_ng::from_str(&yaml).unwrap();
        assert_eq!(parsed, archived);
    }

    #[test]
    fn archived_deserialize_map_without_reason() {
        let yaml = "{}";
        let parsed: Archived = serde_yaml_ng::from_str(yaml).unwrap();
        assert_eq!(parsed, Archived::Yes(ArchivedDetail { reason: None }));
    }

    #[test]
    fn archived_reason_accessor() {
        assert_eq!(Archived::No.reason(), None);
        assert_eq!(Archived::yes().reason(), None);
        assert_eq!(
            Archived::yes_with_reason("test").reason(),
            Some("test")
        );
    }

    #[test]
    fn amendment_with_archived_reason_roundtrips() {
        let yaml = r#"
id: 1
name: test
description: test amendment
targets:
  shape_ids:
  - 1
status: proposed
intent:
  kind: amendment
  summary: test
  source: ai
initiated_by:
  type: ai
archived:
  reason: Changes fully integrated
"#;
        let amendment: Amendment = serde_yaml_ng::from_str(yaml).unwrap();
        assert!(amendment.is_archived());
        assert_eq!(amendment.archived.reason(), Some("Changes fully integrated"));

        let reserialized = serde_yaml_ng::to_string(&amendment).unwrap();
        let reparsed: Amendment = serde_yaml_ng::from_str(&reserialized).unwrap();
        assert_eq!(reparsed.archived, amendment.archived);
    }

    #[test]
    fn amendment_with_bare_archived_true_still_works() {
        let yaml = r#"
id: 1
name: test
description: test amendment
targets:
  shape_ids:
  - 1
status: proposed
intent:
  kind: amendment
  summary: test
  source: ai
initiated_by:
  type: ai
archived: true
"#;
        let amendment: Amendment = serde_yaml_ng::from_str(yaml).unwrap();
        assert!(amendment.is_archived());
        assert_eq!(amendment.archived.reason(), None);
    }
}
