//! The [`Amendment`] node — an immutable change record evolving the
//! shape and constraint graphs over time.
//!
//! Once a shape or constraint reaches `promoted` or `canonical`, all
//! subsequent changes are recorded as Amendments rather than direct
//! edits. Each amendment carries `targets` (the IDs it modifies),
//! `initiated_by` (human / ai / system), and the standard intent +
//! evidence + provenance fields.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use clap::ValueEnum;

use super::{
    AmendmentId, ConstraintId, Evidence, Intent, ProfileId, Provenance, Realization, ShapeId,
    Status,
};

/// Semver-style impact classification for an amendment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VersionImpact {
    /// Breaking change.
    Major,
    /// Backwards-compatible enhancement.
    Minor,
    /// Backwards-compatible fix.
    Patch,
}

/// Who initiated an amendment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InitiatedType {
    /// Authored directly by a human.
    Human,
    /// Authored by an AI agent.
    Ai,
    /// Generated by an automated system or migration.
    System,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Amendment {
    pub id: AmendmentId,
    pub name: String,
    pub description: String,
    pub targets: AmendmentTargets,
    pub status: Status,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_impact: Option<VersionImpact>,
    pub intent: Intent,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub constraints: Vec<ConstraintId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub realization: Vec<Realization>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub evidence: Vec<Evidence>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub provenance: Vec<Provenance>,
    pub initiated_by: InitiatedBy,
    /// Display-only archival state. When present, the amendment is
    /// hidden from listing output by default. Validation, reciprocity
    /// (INV-019), and CI-002 enforcement always see the full set
    /// regardless of this field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub archived: Option<ArchivedDetail>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub metadata: BTreeMap<String, serde_yaml_ng::Value>,
}

impl Amendment {
    /// Returns `true` when this amendment has been archived and should
    /// be hidden from default listing output.
    #[must_use]
    pub fn is_archived(&self) -> bool {
        self.archived.is_some()
    }

}

impl super::traits::GraphNode for Amendment {
    type Id = super::AmendmentId;

    fn raw_id(&self) -> u64 {
        self.id.get()
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn status(&self) -> &super::Status {
        &self.status
    }

    fn intent(&self) -> &super::Intent {
        &self.intent
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AmendmentTargets {
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub shape_ids: Vec<ShapeId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub constraint_ids: Vec<ConstraintId>,
    #[serde(
        default,
        deserialize_with = "crate::model::serde_helpers::null_to_default",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub profile_ids: Vec<ProfileId>,
}

impl AmendmentTargets {
    /// Returns `true` when the amendment targets no nodes at all.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.shape_ids.is_empty() && self.constraint_ids.is_empty() && self.profile_ids.is_empty()
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InitiatedBy {
    #[serde(rename = "type")]
    pub initiated_type: InitiatedType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<String>,
}

/// Detail attached when an amendment is archived.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ArchivedDetail {
    /// Required explanation of why this amendment was archived.
    pub reason: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn archived_object_roundtrips() {
        let detail = ArchivedDetail {
            reason: "Changes integrated".into(),
        };
        let yaml = serde_yaml_ng::to_string(&detail).unwrap();
        assert!(yaml.contains("reason"));
        assert!(yaml.contains("Changes integrated"));
        let parsed: ArchivedDetail = serde_yaml_ng::from_str(&yaml).unwrap();
        assert_eq!(parsed, detail);
    }

    #[test]
    fn amendment_with_archived_roundtrips() {
        let yaml = r#"
id: 1
name: test
description: test amendment
targets:
  shape_ids:
  - 1
status: proposed
intent:
  kind: amendment
  summary: test
  source: ai
initiated_by:
  type: ai
archived:
  reason: Changes fully integrated
"#;
        let amendment: Amendment = serde_yaml_ng::from_str(yaml).unwrap();
        assert!(amendment.is_archived());
        assert_eq!(
            amendment.archived.as_ref().map(|d| d.reason.as_str()),
            Some("Changes fully integrated")
        );

        let reserialized = serde_yaml_ng::to_string(&amendment).unwrap();
        let reparsed: Amendment = serde_yaml_ng::from_str(&reserialized).unwrap();
        assert_eq!(reparsed.archived, amendment.archived);
    }

    #[test]
    fn amendment_without_archived_roundtrips() {
        let yaml = r#"
id: 1
name: test
description: test amendment
targets:
  shape_ids:
  - 1
status: proposed
intent:
  kind: amendment
  summary: test
  source: ai
initiated_by:
  type: ai
"#;
        let amendment: Amendment = serde_yaml_ng::from_str(yaml).unwrap();
        assert!(!amendment.is_archived());
        assert!(amendment.archived.is_none());
    }
}
