//! Newtype wrappers around the raw `u64` identifiers used for each node
//! type in the shapes graph.
//!
//! Each `*Id` type is a transparent wrapper that encodes — at the type
//! level — *which* kind of node an identifier belongs to. This makes it
//! impossible to accidentally pass a [`ShapeId`] where a [`ConstraintId`]
//! is expected, while still serializing as a bare integer in YAML and
//! JSON. See constraint 13 (Newtype ID Safety) in `.shapes/`.
//!
//! All four types are generated by the `define_id!` macro and implement
//! the [`NodeId`] trait, per constraint 39 (NodeId Macro Generation).

use crate::model::NodeType;

/// Common behavior shared by all node identifier newtypes.
///
/// Every ID wraps a `u64` and supports `Copy + Eq + Hash + Ord +
/// Display`. This trait lets generic code convert between the typed
/// wrapper and the raw integer without knowing which node kind it is.
/// The [`NODE_TYPE`](Self::NODE_TYPE) constant enables
/// `store.load::<T>(T::Id::NODE_TYPE, raw)` patterns.
pub trait NodeId:
    Copy + Eq + Ord + std::hash::Hash + std::fmt::Display + Send + Sync + 'static
{
    /// The [`NodeType`] this identifier belongs to.
    const NODE_TYPE: NodeType;

    /// Wraps a raw `u64` as a typed identifier.
    ///
    /// Currently called through concrete types (e.g. `ShapeId::new`),
    /// not through the trait bound. Retained for generic node
    /// construction in future code (e.g. `N::Id::new(raw)`).
    #[allow(dead_code)]
    fn new(raw: u64) -> Self;

    /// Returns the underlying raw `u64`.
    fn get(self) -> u64;
}

/// Declares a newtype `$Name(u64)` with `new`, `get`, `Display`,
/// `FromStr`, transparent serde, and a [`NodeId`] implementation.
///
/// All four ID types in the shapes graph are generated by this macro.
/// See constraint 39 (NodeId Macro Generation) in `.shapes/`.
macro_rules! define_id {
    (
        $(#[doc = $doc:expr])*
        $Name:ident => $node_type:expr
    ) => {
        $(#[doc = $doc])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord,
            serde::Serialize, serde::Deserialize,
        )]
        #[serde(transparent)]
        pub struct $Name(u64);

        impl $Name {
            /// Wraps a raw `u64` as a typed identifier.
            #[must_use]
            pub fn new(raw: u64) -> Self {
                Self(raw)
            }

            /// Returns the underlying raw `u64`.
            #[must_use]
            pub fn get(self) -> u64 {
                self.0
            }
        }

        impl std::fmt::Display for $Name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                self.0.fmt(f)
            }
        }

        impl std::str::FromStr for $Name {
            type Err = std::num::ParseIntError;
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                s.parse::<u64>().map(Self::new)
            }
        }

        impl NodeId for $Name {
            const NODE_TYPE: NodeType = $node_type;

            fn new(raw: u64) -> Self {
                Self(raw)
            }

            fn get(self) -> u64 {
                self.0
            }
        }
    };
}

define_id! {
    /// Identifier for a [`Shape`](super::Shape) node.
    ShapeId => NodeType::Shape
}

define_id! {
    /// Identifier for a [`Constraint`](super::Constraint) node.
    ConstraintId => NodeType::Constraint
}

define_id! {
    /// Identifier for an [`Amendment`](super::Amendment) node.
    AmendmentId => NodeType::Amendment
}

define_id! {
    /// Identifier for a [`Profile`](super::Profile) node.
    ProfileId => NodeType::Profile
}
